[package]
name = "slability"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
crossterm = { version = "0.26.1" }
tui = { version = "0.19.0",features = ["crossterm"] }